### ISSUE TITLE
Not able to analyze results if one case failed

### ISSUE THREAD

**Issue by Matt-haug** [scottshambaugh/monaco#10]
Hi Scott,

Thank you for your work ! I find the library very handy to use and result oriented.

I face an issue when a sample case simulation fails. Even if one case fails, the simulation crashes. The failure happens in the genOutVars function from the Sim class. When it tries to add the OutVar value of the failed case to the outvals list, it finds no key or value to add since this case failed.
Is there a way to just ignore the failing case and output all the other ones ?

I can't identify if the failure comes from monaco or from my model. I tried to narrow the distribution range of the input variables of my model but nothing changed.

Thank you for your answer,

Matt

![image](https://github.com/scottshambaugh/monaco/assets/132342382/6c3f6f67-1f37-495c-8c9e-84844328faff)

**Comment by Matt-haug** [comment]
It seems now that the failure of some cases comes from my model. But anyway, is there a way to ignore those failed cases to pursue the simulation ?

**Comment by scottshambaugh** [comment]
Hi @Matt-haug, the intention is that setting `debug = False` (the default) when initializing the `Sim` object will allow for skipping errors in the preprocessing, running, or postprocessing steps. However, this appears to not be working well for multithreaded/parallel runs using the dask backend. I'll dig into this, but as a workaround in the meantime you can switch to running with `debug = False` and `singlethreaded = True`.

Although I'll note that as you've found, I would generally recommend running with `debug = True` since it will let you catch errors in your model!

**Comment by scottshambaugh** [comment]
_(Deleted my pervious comment since it was an issue with my tests, not the code)_

Hi @Matt-haug, glad the library is useful! Setting `debug = False` (the default) when initializing the Sim object should allow for skipping errors in the preprocessing, running, or postprocessing steps. Although I'll note that as you've found, I would generally recommend running with `debug = True` since it will let you catch errors in your model. Perhaps the most efficient way to do this is:

```python
sim.debug = False
sim.runSim()

# Then if any cases fail, dig into them:
sim.debug = True
sim.runIncompleteSim()  # will run only the failed cases
```

I just added some tests to the automated suite that should ensure that the debug flag is working as intended: https://github.com/scottshambaugh/monaco/commit/2dadbdb4d12eaf13f5eee0d08853949ffb88f771

Please let me know if you run into more issues!
