### ISSUE TITLE
Case invals are empty when using importInVars

### ISSUE THREAD

**Issue by MariovdBerg** [scottshambaugh/monaco#9]
Hi Scott,

As a follow up on Issue #8, the imported InVars are not added to the cases. Running any sensitivity analysis results in nothing.

Kind regards,

Mario

**Comment by scottshambaugh** [comment]
Cases not being populated is definitely a bug, thanks!

For sensitivity analysis however, it operates in percentile space for the input variables, and this information is not known when loading from file since that only loads values and the input distribution is not known. See: https://github.com/scottshambaugh/monaco/blob/aeeebcdff730aac22a4efb227c4d5f483b56a1bd/src/monaco/dvars_sensitivity.py#L170-L175

For today if you know your input distributions (hopefully you do!), then you could manually set `sim.invars['Var1'].pcts` by calculating those percentiles from the CDF of your distribution. For the future, I think there should be an option to do this automatically when loading from file, so I'll take a stab at implementing that on Sunday. Keeping this issue open for now until that's in.

**Comment by MariovdBerg** [comment]
Aha, I didn't know it was operating in the percentile space. That might just solve it for me, I will test it (I do know the distributions!). 

To automatically do this from file, options I'm thinking of simply have a secondary file that contains the `dist` and `distkwargs`? Or have something similar to a nummap as an optional argument to map this?

**Comment by scottshambaugh** [comment]
Hi @MariovdBerg, this should be working now with v0.12.0! Cases are populated properly now. 

And now when you import invars you can pass in a list of `dists` and `distskwargs` to specify those and automatically repopulate the percentiles and distribution info. Additionally, I fixed passing in `nummaps` when importing invars and outvars, so you should be able to handle number to value conversions better now. Let me know if you run into any more issues!
